apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-deployment-1
spec:
  selector:
    matchLabels:
      app: devops-project-app-1
  template:
    metadata:
      labels:
        app: devops-project-app-1
    spec:
      containers:
      - name: devops-project-app-container-1
        image: darktang3nt/complete-production-e2e-pipeline-project:1.0.0-27
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
